name: Deploy Subgraph to Goldsky

on:
  workflow_dispatch:    

permissions:
  contents: read

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    environment: goldsky-chiado-subgraph
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969 # v2.4.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: Set up Node.js
        uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
        with:
          node-version: 18

      - name: Install the dependencies
        run: yarn install
        
      - name: Build the subgraph
        run: |
          yarn gen-chiado
          yarn build

      - name: Authenticate with Goldsky
        run: yarn goldsky login --token "${{ secrets.GOLDSKY_AUTH_TOKEN }}"

      - name: Deploy the subgraph
        run: yarn deploy-chiado-goldsky
